import MovieTable from '@/components/movie-list'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='m-auto max-w-4xl'>
        <h1 className='text-3xl mb-4'>Movie List</h1>
        <MovieTable />
      </main>
    </>
  )
}
